
server:
  port: 9090

spring:
  boot:
    admin:
      instance-auth:
        enabled: true
        default-user-name: user
        default-password: password

logging:
  level:
    org.springframework.security: trace