#spring.thymeleaf.cache=false

spring:
#  sql:
#    init:
#      mode: embedded
#      data-locations: classpath:data.sql # 实际没生效，不知道为什么
#      schema-locations: classpath:schema.sql
  datasource:
    generate-unique-name: false
    name: tacocloud

  security:
    oauth2:
      client:
        registration:
          facebook: # 使用 facebook 登录的配置
            client-id: <facebook client id>
            client-secret: <facebook client secret>
            scope:
              - email
              - public_profile

#  profiles:
#    active:
#      - prod

#server:
#  port: 0 # 设置为 0 时，会任选可用端口启动

server:
  ssl:
    key-store: classpath:mykeys.jks
    key-store-password: letmein
    key-password: letmein
  port: 8443

taco:
  orders:
    pageSize: 10