spring:
  security:
    oauth2:
      client:
        registration:
          taco-admin-client:
            provider: taco-cloud
            client-id: taco-admin-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8082/login/oauth2/code/{registrationId}
            scope: writeIngredients,deleteIngredients # not to add openid now
        provider:
          taco-cloud:
            authorization-uri: http://authserver:8081/oauth2/authorize
            token-uri: http://authserver:8081/oauth2/token
server:
  port: 8082