
server:
  shutdown: graceful

management:
  endpoints:
    web:
#      base-path: /management # change basic path
      exposure:
        include: '*'
#        exclude: threaddump,heapdump
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # 启用存活和就绪探针
  info:
    env:
      enabled: true
    git:
      mode: full
      enabled: true

# /info will contain this
info:
  contact:
    email: support@tacocloud.com
    phone: 822-625-6831

#  Failed to register application as Application(name=taco-cloud, managementUrl=http://localhost:8080/actuator,
#  healthUrl=http://localhost:8080/actuator/health, serviceUrl=http://host.docker.internal:8080/) at spring-boot-admin

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s # 优雅关机时间
  jmx:
    enabled: true
  application:
    name: taco-cloud
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          management-base-url: http://localhost:8080
          service-url: http://localhost:8080
          metadata:
            user.name: user
            user.password: password
        username: user
        password: password

#        instance:
#          metadata:
#            user.name: admin
#            user.password: 53cr3t

